### ISSUE TITLE
Documentation lists conda being installed in the ubuntu image though the command is not found

### ISSUE THREAD

**Issue by DanielSmitHAW-Alternative** [devcontainers/templates#127]
The [documentation](https://github.com/devcontainers/templates/blob/main/src/ubuntu/README.md) describes conda being installed:
> Using Conda
> This dev container and its associated image includes [the conda package manager](https://aka.ms/vscode-remote/conda/about).

The `conda` command in the the `jammy` version is not found. Does not seem to be installed either.

**Comment by samruddhikhandale** [comment]
Thanks for reporting, opened https://github.com/devcontainers/templates/pull/128 which removes the incorrect info.
