### ISSUE TITLE
[.NET] Add .NET Global tools to Path

### ISSUE THREAD

**Issue by cmaneu** [devcontainers/templates#137]
.NET Global tools are increasingly used by .NET developers, and most notably by .NET developers doing data work (through Entity Framework or Polyglot Notebooks). 

By default, when using .NET on linux, the folder containing the global tools is not added to the PATH. That's the case for `dotnet-mssql` or `dotnet-postgres` templates. This breaks core scenarios, like using Polyglot Notebooks extensions with SQL.

The solution is to add the .NET path to the PATH.

Note: it's also the case for `dotnet` template. However, this template has no Dockerfile, and I'm not sure using the `postCreateCommand` is an appropriate use.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for reporting the issue, added my thoughts to the PR --> https://github.com/devcontainers/templates/pull/138#pullrequestreview-1333417335

**Comment by cmaneu** [comment]
Superseed by https://github.com/devcontainers/images/pull/495
