### ISSUE TITLE
Packages?

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/templates#19]
I can't see the packages from my account, is this normal?
(I'm wondering if they are set to public.)

![image](https://user-images.githubusercontent.com/50911393/195102879-f78c26bc-f7fe-43e0-ae89-488ee85dd9bd.png)

**Comment by eitsupi** [comment]
Glad to hear that!
Looking forward to the new UX.

**Comment by samruddhikhandale** [comment]
Closing this issue as packages are now visible!
