### ISSUE TITLE
Question on Debian / Ubuntu & Centos/RHEL/Azure Linux family of support

### ISSUE THREAD

**Issue by karianna** [devcontainers/templates#196]
Hi all,

Was curious about the default of Debian for this repo.  Do we want to also cover other Debian based flavours or CentOS based flavours?

**Comment by samruddhikhandale** [comment]
Hi 👋 

The Templates are a combination of the [dev container images](https://github.com/devcontainers/images) and [Features](https://github.com/devcontainers/features). 

Currently, the images are debian and ubuntu based, and similarly majority of the Features are debian and ubuntu based (few exceptions to the [common-utils](https://github.com/devcontainers/features/tree/main/src/common-utils) and [nix](https://github.com/devcontainers/features/tree/main/src/nix) Feature which supports CentOS/RHEL/Fedora/Rocky/Alpine).

That said, we would be interested in extending the current support of Templates to other flavors of Linux as well. However, that would need an updated support for the images and Features. 

Hope that makes sense, feel free to ask any followup questions!
