### ISSUE TITLE
Writing a VSCode extension, want to enable "Attach Visual Studio Code" to kubectl pod 

### ISSUE THREAD

**Issue by benjiebob** [devcontainers/templates#199]
Hi there!

I'm writing a VSCode extension and want to be able to add an "Attach Visual Studio Code" to a Kubectl pod button to my UI. I want to build an experience that closely matches [this Kubernetes demo](https://code.visualstudio.com/docs/devcontainers/attach-container) (but with my own custom list of pods). However, after a few days looking through this repo, I'm still struggling to find how to implement this.

Screenshot from Kubernetes demo is here: ![k8s-attach](https://github.com/devcontainers/templates/assets/17785299/04d806c3-8682-4ec2-8f4f-a9181dcee1c1)

I'd be really grateful if you could either point me towards a tutorial for setting this up, or if you could explain the steps that would be great.

Thanks!
Ben

**Comment by bamurtaugh** [comment]
Thanks for opening! If you install the VS Code Dev Containers extension and right click, I believe this attach option is added when exploring containers from the Docker extension. Does installing the Dev Containers extension help?

**Comment by benjiebob** [comment]
Yes, sorry if I wasn't clear enough. I am trying to add a "Attach Visual Studio Code" _to my own VSCode extension_ so I need to know the code behind how this feature is implemented.

**Comment by benjiebob** [comment]
I've been doing some digging and found a seemingly related [question](https://stackoverflow.com/questions/60379221/how-to-attach-a-remote-container-using-vscode-command-line) that proposes the following syntax: 
```bash
code --folder-uri "vscode-remote://attached-container+<SOMETHING>"
```

I suspect that the "Attach Visual Studio Code" menu option I screenshotted above is launching a terminal command like this. I've tried lots of variants of hex values etc. to try and launch a VSCode window connected to my kubectl pod but haven't yet had any success. 

I'd be really grateful if you could share the command to connect to a pod (shown graphically [here](https://code.visualstudio.com/docs/devcontainers/attach-container#_attach-to-a-container-in-a-kubernetes-cluster)).  

Thanks!

**Comment by benjiebob** [comment]
Aha, I found the answer. This fantastic contributor [solved it](https://github.com/microsoft/vscode-remote-release/issues/5849#issuecomment-974784657). 

```python
cmd = f"code --folder-uri "vscode-remote://k8s-container%2Bcontext%3D{context}+podname={podname}+namespace={namespace}+name={container_name}{some_path}"
```
Be careful to escape any slashes with %2F in the URI.
