### ISSUE TITLE
invalid licenseURL

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/templates#20]
These do not seem to be working?

https://github.com/devcontainers/templates/blob/c58f2c1664c5ceb9fd674fbb846de1a2979f5cdc/src/alpine/devcontainer-template.json#L8

**Comment by samruddhikhandale** [comment]
Thanks for catching! ✨  
Fixed 
https://github.com/devcontainers/templates/blob/main/src/alpine/devcontainer-template.json#L8
