### ISSUE TITLE
Request: a devcontainer suitable for developing Electron applications

### ISSUE THREAD

**Issue by jorroll** [devcontainers/templates#200]
This is a feature request for a devcontainer template suitable for developing [Electron](https://www.electronjs.org/) applications. As far as I can tell, none of the existing devcontainer templates can be used for this task (attempting to run electron results in various errors due to missing dependencies and misconfigured settings).

**Comment by samruddhikhandale** [comment]
Hi 👋 

We appreciate your request for adding a new Template, however, we only plan on accepting improvement and bug fix requests for the [current set of maintained Templates](https://github.com/devcontainers/templates/blob/main/src). Hence, we don't have any current plans of supporting a new Electron Template.

Instead, we motivate the community to create Templates in a separate repository of their control, which they could share with the community.  @jorroll Would you be interested in creating one? The [devcontainers/template-starter](https://github.com/devcontainers/template-starter) repo has more guidance on self authoring them.

Once you've self authored and if you'd like to share it with the community, we'd recommend [adding it to the index](https://github.com/devcontainers/template-starter#adding-templates-to-the-index). It will make them visible in our [supporting tools](https://containers.dev/supporting) (like https://containers.dev/templates, Dev Containers Extension, GitHub Codespaces etc).

Feel free to ask any questions/queries along the way, feedbacks are welcome too!

**Comment by jorroll** [comment]
> we don't have any current plans of supporting a new Electron Template

👍 

> @jorroll Would you be interested in creating one?

I opened this issue after failing to get electron to work inside a devcontainer. So no, this isn't something I'm able to do.
