### ISSUE TITLE
include C# Dev Kit in dotnet template

### ISSUE THREAD

**Issue by carlin-q-scott** [devcontainers/templates#226]
```json
"customizations": {
	"vscode": {
		"extensions": [
			"ms-dotnettools.csdevkit"
		]
	}
}
```

**Comment by eljog** [comment]
The base image used by this template comes with the `ms-dotnettools.csharp` extension [here](https://github.com/devcontainers/images/blob/5bef10a5d4732a27bee2ddd314afb305a0bd1e71/src/dotnet/.devcontainer/devcontainer.json#L27-L29).
Could you please share more details on how this additional extension can be helpful to the users?

If the community finds it's beneficial, it'd be great if you would consider contributing a PR to add the extension to the [base image](https://github.com/devcontainers/images/tree/main/src/dotnet) itself.
Thank you

**Comment by bamurtaugh** [comment]
Thanks for opening!

For further context, we did explore this last year: https://github.com/devcontainers/templates/issues/164.

**Comment by bamurtaugh** [comment]
I'm going to close this as not planned at the moment based on the exploration in https://github.com/devcontainers/templates/issues/164, but please let me know if you have any other questions/thoughts, and happy to discuss further!
