### ISSUE TITLE
javascript-node-mongo not building the container

### ISSUE THREAD

**Issue by wguerram** [devcontainers/templates#230]
Hi, I'm creating a dev container based on javascript-node-mongo template, but it seems the urls in the Dockerfile is not well.

Is someone else having this issue?

`[app dev_container_auto_added_stage_label 2/3] RUN . /etc/os-release     && curl -sSL "https://www.mongodb.org/static/pgp/server-6.0.asc" | gpg --dearmor > /usr/share/keyrings/mongodb-archive-keyring.gpg     && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/mongodb-archive-keyring.gpg] http://repo.mongodb.org/apt/debian ${VERSION_CODENAME}/mongodb-org/6.0 main" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list     && apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get install -y mongodb-mongosh     && if [ "$(dpkg --print-architecture)" = "amd64" ]; then apt-get install -y mongodb-database-tools; fi     && apt-get clean -y && rm -rf /var/lib/apt/lists/*:
1.597 deb [arch=amd64 signed-by=/usr/share/keyrings/mongodb-archive-keyring.gpg] http://repo.mongodb.org/apt/debian bullseye/mongodb-org/6.0 main
2.040 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]`

**Comment by samruddhikhandale** [comment]
Hi 👋 

I built a dev container with the default [javascript-node-mongo](https://github.com/devcontainers/templates/tree/main/src/javascript-node-mongo) Template, and it was created successfully. 

It used the default `20-bullseye` Node version, @wguerram which Node version did you use for configuring the Template? 

> but it seems the urls in the Dockerfile is not well.

Can you help paste the error message? Thanks!

**Comment by wguerram** [comment]
@samruddhikhandale thanks for your kindness on taking a look. You're are right, it works fine. I think was a firewall blocking something. I'm on a different nerwork.
