### ISSUE TITLE
Could not connect to mariaDB with imageVariant default

### ISSUE THREAD

**Issue by espdesign** [devcontainers/templates#233]
_I am very new to this_ but I wanted to share an issue that took me a while to diagnose and understand 
I wanted to share in case it needs to be clarified for other new people. 

I attempted to use the template php-mariadb and selected the default image variant. 
everything seemed fine with no errors made evident.

I used the command to try to connect to mariadb.
`mariadb -h localhost -P 3306 -u root -p`

I could not connect to the mariadb it kept throwing me the error. 
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)`

I kept reading the readme at https://github.com/devcontainers/templates/tree/main/src/php-mariadb 
And could not find a solution to my issue.

Turns out the image variant defaults to `bullseye`. and this was the problem. as soon as i switched to `bookworm` I could now connect no problem.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for flagging this issue and adding a solution.

When `bookworm` was newly supported, I remember [php-mariadb](https://github.com/devcontainers/templates/tree/main/src/php-mariadb) failing with `mySQL` errors as it didn't immediately support it. Hence, we kept the default as `bullseye`.

Looks like we can update the default now, thanks! Will shortly create a PR.
