### ISSUE TITLE
docker-from-docker?

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/templates#24]
Same as devcontainers/features#123

Generally this is referred to as "Docker outside of Docker" (DooD), like "Docker in Docker" (DinD), so a name change may make sense.

**Comment by samruddhikhandale** [comment]
@Chuxel / @joshspicer Any concerns with renaming the Template?

It is currently only used by `Add Dev Container Configuration Files` command which dynamically reads data from a `index.json` file. I think it would be safe to simply rename the template and regenerate the index.

**Comment by Chuxel** [comment]
Nope!  As discussed for the feature, that's fine with me!

**Comment by samruddhikhandale** [comment]
Renamed and published `docker outside of docker` Templates 🚀 

![image](https://user-images.githubusercontent.com/24955913/204357201-969be006-e809-402a-a40a-5178e2b627eb.png)
