### ISSUE TITLE
Stuck in "Replacing imageVariant with ..." step

### ISSUE THREAD

**Issue by ysazak** [devcontainers/templates#242]
Hi,

When I try to create a Dev container with any template, it always stucks in "Replacing imageVariant with ..." step. Any idea what the problem is?

Example templates:

- javascript-node:latest
- typescript-node:latest

Log:
```
[22098 ms] [2024-02-25T21:32:56.429Z] Start: Run: docker-credential-wincred get
[22169 ms] [2024-02-25T21:32:56.500Z] Stop (71 ms): Run: docker-credential-wincred get
[22898 ms] [2024-02-25T21:32:57.230Z] Replacing imageVariant with 18-buster
```

Note: I use Rancher Desktop v1.12.3 with dockerd (moby) enabled

**Comment by samruddhikhandale** [comment]
@gauravsaini04 Can you help investigate this issue? Thanks!

**Comment by philipf** [comment]
Same issue for me.

Running:
- VS Code 1.88.1
- Dev Containers v0.354.0
- Rancher Desktop v1.13.1

I can run existing DevContainers, this issue only present itself when creating new Dev Containers.

```
[135771 ms] [2024-04-18T04:46:16.041Z] Start: Run: docker-credential-wincred get
[135827 ms] [2024-04-18T04:46:16.097Z] Stop (56 ms): Run: docker-credential-wincred get
[137147 ms] [2024-04-18T04:46:17.418Z] Replacing imageVariant with 3.12-bullseye
```

It seems to be stuck on creating the `alpine:3.16.3` container.

**Comment by samruddhikhandale** [comment]
Hi 👋 

> When I try to create a Dev container with any template

@ysazak @philipf How are you adding new Templates to your existing dev container? Is it with the `Dev Containers Extension` or with the @devcontainers/cli? Can you explain me your repro steps, thanks!

Curious if you have looked at https://github.com/devcontainers/templates?tab=readme-ov-file#how-can-i-use-the-templates

**Comment by philipf** [comment]
> Hi 👋
> 
> > When I try to create a Dev container with any template
> 
> @ysazak @philipf How are you adding new Templates to your existing dev container? Is it with the `Dev Containers Extension` or with the @devcontainers/cli? Can you explain me your repro steps, thanks!
> 
> Curious if you have looked at https://github.com/devcontainers/templates?tab=readme-ov-file#how-can-i-use-the-templates

I used the `Dev Containers Extension`

**Comment by gauravsaini04** [comment]
hi @ysazak,
Are you still facing this issue ?

**Comment by samruddhikhandale** [comment]
Thanks @philipf for the information, looks like the issue is with the extension and not with the Templates or the CLI. However, the `devcontainers` team does not maintain the `Dev containers` extension.

Can you open an issue in https://github.com/microsoft/vscode-remote-release/issues? The VS Code team should be able to help you provide guidance. Thanks!

**Comment by andi-blafasl** [comment]
I'm experiencing the exact same behavior with Rancher Desktop. Switching vom Rancher to Docker Desktop, everything is working fine.
