### ISSUE TITLE
I am a greener. Just ask a simple question about the toolchain in the container.

### ISSUE THREAD

**Issue by lmmqxyx404** [devcontainers/templates#243]
```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/rust
{
	"name": "Rust",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/rust:1-1-bullseye"

	// Use 'mounts' to make the cargo cache persistent in a Docker Volume.
	// "mounts": [
	// 	{
	// 		"source": "devcontainer-cargo-cache-${devcontainerId}",
	// 		"target": "/usr/local/cargo",
	// 		"type": "volume"
	// 	}
	// ]

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "rustc --version",

	// Configure tool-specific properties.
	// "customizations": {},

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```
I had added the rust dev container. But I stiil need a cmake. How can I add the cmake?
And if I want to upgrade the rust version, What can I do ?

**Comment by samruddhikhandale** [comment]
Hello 👋 

> And if I want to upgrade the rust version, What can I do ?

We try to keep the `mcr.microsoft.com/devcontainers/rust:1-1-bullseye` image up-to-date. However, you can install another version of rust with the [Rust Feature](https://github.com/devcontainers/features/tree/main/src/rust).

Feel free to look at https://containers.dev/ for more information.

>  But I stiil need a cmake. How can I add the cmake?

You can use a `Dockerfile` instead with the following contents and point the `devcontainer.json` to use it (ie In your `devcontainer.json` file, make sure to set `"dockerfile": "Dockerfile"` to use the Dockerfile you just created). Read more at https://containers.dev/guide/dockerfile

```
FROM mcr.microsoft.com/devcontainers/rust:1-1-bullseye

# Install CMake
RUN apt-get update && \
    apt-get -y install cmake
```
