### ISSUE TITLE
SSH key sharing works only for 0-20

### ISSUE THREAD

**Issue by Azel-ytof** [devcontainers/templates#249]
Hi,

I've done all things to share my SSH key to access my gitlab repositories.
But the problem is that I get the git permission denied error.

In fact, I have test these images :

- mcr.microsoft.com/devcontainers/typescript-node
- mcr.microsoft.com/devcontainers/typescript-node:20
- mcr.microsoft.com/devcontainers/typescript-node:1-20
- mcr.microsoft.com/devcontainers/typescript-node:0-20

I've got the problem with all of this except for the 0-20, which works perfectly.
I don't understand why this happen, and I'm not an expert of devcontainers so I don't know where to search.

Have you an idea of where is the problem and is it resolvable ?

May you need more information ?

**Comment by samruddhikhandale** [comment]
Hi 👋 

> I've got the problem with all of this except for the 0-20, which works perfectly.

With a newer major version for the image, the only breaking change was update the default distro to bookworm.

@Azel-ytof Can you try if this image works? 👇 

```
mcr.microsoft.com/devcontainers/typescript-node:20-bullseye
```

Also, here are a few things you could try:

- Check if the SSH keys are correctly mounted in the containers. You can do this by running ls -la ~/.ssh in the terminal of the devcontainer. You should see your SSH keys listed.
- Ensure that the SSH keys have the correct permissions. The private key should have permissions set to 600 (-rw-------). You can set this by running chmod 600 ~/.ssh/id_rsa in the devcontainer terminal.
- Make sure the SSH agent is running and your key is added. You can check this by running ssh-add -l in the dev container terminal. If your key is not listed, you can add it with ssh-add ~/.ssh/id_rsa.

Remember to replace `id_rsa` with the name of your SSH key if it's different. If you're still having issues after trying these steps, please provide more information about the error messages you're seeing and any relevant configuration files.

**Comment by Azel-ytof** [comment]
Hi @samruddhikhandale,

It works with the given image...

`ls -la ~/.ssh` : I only have known_hosts, no my id_ed25519 keys...
But it is the same thing in working images (20-bullseye and 0-20), so I don't think it comes from there.

**Comment by samruddhikhandale** [comment]
Looks it's relevant to the `bookworm` distro, hence, it looks similar to https://github.com/devcontainers/images/issues/768 

Let's us that issue for tracking, thanks!

**Comment by samruddhikhandale** [comment]
Closing as this looks like an upstream issue!

Might be worth looking at https://github.com/microsoft/vscode-remote-release/issues/7525#issuecomment-1354742843 and upgrading OpenSSH for Windows.

Ref: https://github.com/devcontainers/images/issues/768#issuecomment-2030047224
