### ISSUE TITLE
Switch the default variant of Ubuntu version to `jammy`?

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/templates#27]
Same as devcontainers/images#170, related to devcontainers/images#185

https://github.com/devcontainers/templates/blob/5bec7790a36127ec0858e8676e1351f1fdf3a87d/src/ubuntu/devcontainer-template.json#L18

**Comment by samruddhikhandale** [comment]
Already addressed in https://github.com/devcontainers/templates/pull/26/files#diff-13835fe46c02fdefe709f50cce5911897d5d99635e39e9373802ddbd70b1a09dL18

![image](https://user-images.githubusercontent.com/24955913/199061942-f3dffc08-79d2-4f7e-9540-b838e4f06701.png)

Closing as completed 🚀
