### ISSUE TITLE
Update action versions

### ISSUE THREAD

**Issue by gvatsal60** [devcontainers/templates#296]
- Update Action version to latest

**Comment by bamurtaugh** [comment]
If you have more details on what updates you'd like to see, please let us know, or even feel free to contribute a PR (I'd be happy to review it if you tag me in it). Thanks so much!

**Comment by gvatsal60** [comment]
Hi @bamurtaugh,

Could you please have a look at the PR for #297 ? 
I submitted it earlier but forgot to link it to the issue. Apologies for the oversight.
