### ISSUE TITLE
/workspace/{project_dir_name} shows docker image ID

### ISSUE THREAD

**Issue by opmtk** [devcontainers/templates#301]
I'm using the cpp template for devcontainer in VSCode win Win10 and Docker-Desktop/WSL (Docker Desktop 4.35.1). All builds and starts fine, but I have a mount bind to my project folder of `/workspaces/61983f524eebc68bc72067df821eb9a29c8787120e77c389ae2532fe9279dc88` 

![grafik](https://github.com/user-attachments/assets/48a23079-f71f-4b9b-bcdb-2088fca75419)

which is the ID of Docker(Deskop) Image.

![grafik](https://github.com/user-attachments/assets/64037d9d-bef5-4aab-8f9d-53ce1017df36)

This is not handy for error messages from the compiler, not even in the console/terminal. The result is the same or reproducible, when I create it by using the 'DevContainer' task in VS Code, so I rule out problems with my settings for now.

The problem is very stressful, because every time the paths in the build directory of CMake change! 
The behavior doesn't change if I remove all images, volumes and build caches.

Will it be fixed and what is the temporary solution for this?

**Comment by chrmarti** [comment]
This should be fixed in the latest version. (https://github.com/microsoft/vscode-remote-release/issues/10514)
