### ISSUE TITLE
Name and description are wrong/incomplete in miniconda-postgres template 

### ISSUE THREAD

**Issue by 0xfabioo** [devcontainers/templates#33]
In the devcontainer-template.json file, the name and description are incomplete. A hint about postgres is missing. 

Screenshot from VSCode:

![image](https://user-images.githubusercontent.com/1413985/199939603-c196ec4c-3c60-4c01-9485-65a38054c294.png)

**Comment by samruddhikhandale** [comment]
Thanks for feedback. ✨ 

Updating with https://github.com/devcontainers/templates/pull/35

**Comment by samruddhikhandale** [comment]
Deployed 🚀 

![image](https://user-images.githubusercontent.com/24955913/200400394-243ae995-cf7d-4e8b-8f60-12010e099912.png)
