### ISSUE TITLE
Update .NET C# Image/Template to support & use .NET7

### ISSUE THREAD

**Issue by warrenbuckley** [devcontainers/templates#38]
With the release of .NET7 released this week.
It makes sense if the .NET C# DevContainer template supports .NET7

https://github.com/devcontainers/templates/tree/main/src/dotnet

Currently it only supports the following
* 6.0
* 3.1
* 6.0-bullseye
* 3.1-bullseye
* 6.0-focal
* 3.1-focal

I am not sure who to ping or ask for help with this, I see the latest committer to these files is @samruddhikhandale so perhaps you can help with this?

**Comment by warrenbuckley** [comment]
I can't publicly browse the `mcr.microsoft.com/devcontainers/dotnet` URL,
I can only assume that there is not a prebuilt devcontainer image yet for 7.0

**Comment by samruddhikhandale** [comment]
Yes, in order to update this template we need`mcr.microsoft.com/devcontainers/dotnet:7.0`

Once changes in https://github.com/devcontainers/images/pull/201 are merged & deployed, then I'll work on updating the template.

**Comment by warrenbuckley** [comment]
Additionally, I found the `feature` to add the .NET CLI
https://containers.dev/features
https://github.com/devcontainers/features/tree/main/src/dotnet

Could this be an alternative approach perhaps?

**Comment by samruddhikhandale** [comment]
> Could this be an alternative approach perhaps?

It's a nice suggestion. However, for templates, we are currently following a pattern to use the images for simplicity. If necessary, we then build using Features from https://github.com/devcontainers/features. As we plan to deploy the Images by Monday, I'll quickly update the dotnet Template when images are live. It will avoid changes to the current Template.

In the meanwhile, feel free to use dotnet 7 with Feature as follows -

```
"features": {
    "ghcr.io/devcontainers/features/dotnet:1": {
        "version": "7"
    }
}
```

**Comment by samruddhikhandale** [comment]
@warrenbuckley ℹ️  You can look for all the published tags for dotnet image [here](https://mcr.microsoft.com/v2/devcontainers/dotnet/tags/list)

**Comment by warrenbuckley** [comment]
The feature approach works perfectly fine for me, so thanks @samruddhikhandale to install .NET7 SDK tools

I am not sure why you would not want to use a smaller/slimmer image and then use the features to get the correct SDK version you want to use. For easier maintenance ?

**Comment by samruddhikhandale** [comment]
Updated the Template with .NET 7 options as the corresponding images are live 🚀 

![image](https://user-images.githubusercontent.com/24955913/201804459-eeba303a-da4e-4ed4-acc2-36812a189cce.png)

// cc - @warrenbuckley

**Comment by warrenbuckley** [comment]
Hi @samruddhikhandale 
Will the template for `C# (.NET) and MS SQL` be updated as well?

![image](https://user-images.githubusercontent.com/1389894/201896180-5839cb21-55a3-4af1-902a-1e1db95e893f.png)

![image](https://user-images.githubusercontent.com/1389894/201896307-d42de623-00c1-4aec-8540-8c17fb905c40.png)

**Comment by samruddhikhandale** [comment]
Hi @warrenbuckley  👋 

Yes, I have another PR in review to update those - https://github.com/devcontainers/templates/pull/43

**Comment by samruddhikhandale** [comment]
Updated 🚀
