### ISSUE TITLE
Templates missing header information

### ISSUE THREAD

**Issue by Chuxel** [devcontainers/templates#48]
Classily we've had two comments at the top to help people orient around using dev containers.  First is a link to aka.ms/devcontainer.json, and another is to the README of the template.  I think both of these should continue to be present.  They were auto-added by the build system in the past.

e.g.

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/javascript-node
```

**Comment by samruddhikhandale** [comment]
Closing as completed ✨ 

![image](https://user-images.githubusercontent.com/24955913/203429474-68d24a22-864d-498b-883e-839b0066462a.png)
