### ISSUE TITLE
Bump python version to 3.11

### ISSUE THREAD

**Issue by abdulrabbani00** [devcontainers/templates#50]
Would love to use python 3.11 with the popular python dev containers.

**Comment by Chuxel** [comment]
Python 3.11 is available - how are you trying to use it?

**Comment by samruddhikhandale** [comment]
Thanks @abdulrabbani00 for opening up the PR - https://github.com/devcontainers/templates/pull/51

Python 3.11 options are now available 🚀 

<img width="770" alt="image" src="https://user-images.githubusercontent.com/24955913/202311273-39261b72-1c4c-496e-80c5-e8d785f535dd.png">
