### ISSUE TITLE
Rust: Make bullseye the default (instead of buster)

### ISSUE THREAD

**Issue by chrmarti** [devcontainers/templates#58]
Bullseye is the current stable release and debugging doesn't work on Mac Silicon with buster.

https://github.com/devcontainers/templates/blob/f516bbedc3d7bf60628cd108bb15ea27f826f889/src/rust/devcontainer-template.json#L17

/cc @Chuxel

Thanks.

**Comment by samruddhikhandale** [comment]
Closing as fixed

![image](https://user-images.githubusercontent.com/24955913/203146076-11e01919-1995-431c-9b76-a86d4e96bfea.png)
