### ISSUE TITLE
Is "docker-in-docker" template correct?

### ISSUE THREAD

**Issue by dzeyelid** [devcontainers/templates#73]
When I created an environment by selecting "Docker in Docker" in "Add Dev Container Configuration Files" in VS Code, the template created the `devcontainer.json` below that has `docker-from-docker` in features.

In the environment, the docker engine shows its instance when running `docker ps`. It looks like "docker-from-docker" behavior, not "docker-in-docker'.

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/docker-in-docker
{
	"name": "Docker in Docker",
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",
	"features": {
		"ghcr.io/devcontainers/features/common-utils:1": {
			"installZsh": "true",
			"upgradePackages": "false",
			"uid": "1000",
			"gid": "1000",
			"installOhMyZsh": "true",
			"nonFreePackages": "true"
		},
		"ghcr.io/devcontainers/features/docker-from-docker:1": {
			"version": "latest",
			"enableNonRootDocker": "true",
			"moby": "true"
		}
	}

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "docker --version",

	// Configure tool-specific properties.
	// "customizations": {},

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```

So, I changed from `docker-from-docker` to `docker-in-docker` inside features configuration, then the behavior is suited to my thought.

What do you think?

Thank you for these convenient templates!

Best regards,

**Comment by samruddhikhandale** [comment]
Hi @dzeyelid 👋 

Thanks for reporting.

> So, I changed from docker-from-docker to docker-in-docker inside features configuration, then the behavior is suited to my thought.
> What do you think?

Yep, that should be `docker-in-docker`.  Looks like this was a regression during migration, working on fixing it.

**Comment by samruddhikhandale** [comment]
Closed by the bot as it's fixed. 🚀 

![image](https://user-images.githubusercontent.com/24955913/206532304-78838ded-e324-4682-864a-dc00ebcc2cc1.png)
